# Generated by Django 4.2.16 on 2024-09-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700, unique=True, verbose_name='أسم الفئه')),
                ('languages', models.CharField(choices=[('AR', 'AR'), ('EN', 'EN')], max_length=50, verbose_name='اللغه')),
                ('first_image', models.ImageField(upload_to='media/images/', verbose_name='الصوره')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='حالة الفئه')),
            ],
            options={
                'verbose_name': 'فئه',
                'verbose_name_plural': 'الفئات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='حساب المستخدم')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ اضافته في السله')),
                ('complete', models.BooleanField(default=False, verbose_name='الحاله')),
                ('qty', models.IntegerField(default=1, verbose_name='الكميه')),
                ('item_type', models.CharField(choices=[('product', 'product'), ('promotion', 'promotion')], max_length=10, verbose_name='النوع')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم العرض')),
                ('languages', models.CharField(choices=[('AR', 'AR'), ('EN', 'EN')], max_length=50, verbose_name='اللغه')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='السعر القديم')),
                ('new_price', models.DecimalField(decimal_places=2, default=15, max_digits=7, verbose_name='السعر الجديد')),
                ('first_image', models.ImageField(upload_to='media/images/', verbose_name='الصوره الأولى')),
                ('second_image', models.ImageField(blank=True, upload_to='media/images/', verbose_name='الصوره الثانيه')),
                ('third_image', models.ImageField(blank=True, upload_to='media/images/', verbose_name='الصوره الثالثه')),
                ('fourth_image', models.ImageField(blank=True, upload_to='media/images/', verbose_name='الصوره الرابعه')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='حالة المنتج')),
                ('item_type', models.CharField(choices=[('promotion', 'promotion')], max_length=10, verbose_name='النوع')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='حساب المستخدم')),
                ('customer_name', models.CharField(max_length=200, verbose_name='أسم العميل')),
                ('phone', models.CharField(max_length=100, verbose_name='رقم الهاتف')),
                ('address', models.CharField(max_length=200, verbose_name='العنوان')),
                ('state', models.CharField(max_length=200, verbose_name='المنطقه')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الشراء')),
                ('payment_status', models.BooleanField(default=True, verbose_name='حالة الدفع')),
                ('order', models.ManyToManyField(related_name='orders', to='commerce.orders', verbose_name='الطلب')),
            ],
            options={
                'verbose_name': 'شراء',
                'verbose_name_plural': 'عمليات الشراء',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم المنتج')),
                ('languages', models.CharField(choices=[('AR', 'AR'), ('EN', 'EN')], max_length=50, verbose_name='اللغه')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='السعر')),
                ('price_vat', models.DecimalField(decimal_places=2, default=15, max_digits=7, verbose_name='قيمة الضريبه')),
                ('first_image', models.ImageField(upload_to='media/images/', verbose_name='الصوره الأولى واذا كنت ستضيف كارت شحن اختر الصوره الأولى فقط')),
                ('second_image', models.ImageField(blank=True, upload_to='media/images/', verbose_name='الصوره الثانيه')),
                ('third_image', models.ImageField(blank=True, upload_to='media/images/', verbose_name='الصوره الثالثه')),
                ('fourth_image', models.ImageField(blank=True, upload_to='media/images/', verbose_name='الصوره الرابعه')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='حالة المنتج')),
                ('item_type', models.CharField(choices=[('product', 'product')], max_length=10, verbose_name='النوع')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='commerce.categories', verbose_name='الفئه')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='commerce.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='orders',
            name='promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='commerce.promotion', verbose_name='العرض'),
        ),
    ]
